// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Project struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Task struct {
	ID          int64
	UserID      int64
	ProjectID   sql.NullInt64
	Done        bool
	Description string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        int64
	Email     string
	Hash      []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
