// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type User struct {
	ID        int64
	Email     string
	Hash      []byte
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
