// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  user_id,
  project_id,
  description
) VALUES (?, ?, ?)
RETURNING id, user_id, project_id, done, description, created_at, updated_at, due
`

type CreateTaskParams struct {
	UserID      int64
	ProjectID   sql.NullInt64
	Description string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.UserID, arg.ProjectID, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Done,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Due,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, done, description, created_at, updated_at, due
FROM tasks
WHERE user_id = ?
AND id = ?
`

type GetTaskParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.UserID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Done,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Due,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, project_id, done, description, created_at, updated_at, due
FROM tasks
WHERE user_id = ?
AND done = FALSE
ORDER BY due ASC, created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Done,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, user_id, project_id, done, description, created_at, updated_at, due
FROM tasks
WHERE user_id = ?
AND project_id = ?
AND done = FALSE
ORDER BY due ASC, created_at DESC
`

type ListTasksByProjectParams struct {
	UserID    int64
	ProjectID sql.NullInt64
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Done,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDone = `-- name: ListTasksDone :many
SELECT id, user_id, project_id, done, description, created_at, updated_at, due
FROM tasks
WHERE user_id = ?
AND done = TRUE
`

func (q *Queries) ListTasksDone(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDone, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Done,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDoneByProject = `-- name: ListTasksDoneByProject :many
SELECT id, user_id, project_id, done, description, created_at, updated_at, due
FROM tasks
WHERE user_id = ?
AND project_id = ?
AND done = TRUE
ORDER BY due ASC, created_at DESC
`

type ListTasksDoneByProjectParams struct {
	UserID    int64
	ProjectID sql.NullInt64
}

func (q *Queries) ListTasksDoneByProject(ctx context.Context, arg ListTasksDoneByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDoneByProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Done,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Due,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDone = `-- name: MarkTaskDone :one
UPDATE tasks
SET done = TRUE
WHERE id = ?
AND user_id = ?
RETURNING id, user_id, project_id, done, description, created_at, updated_at, due
`

type MarkTaskDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, markTaskDone, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Done,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Due,
	)
	return i, err
}
