// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  hash
) VALUES (?, ?)
RETURNING id, email, hash, created_at, updated_at
`

type CreateUserParams struct {
	Email string
	Hash  []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
